/*
 * This file is generated by jOOQ.
 */
package com.example.videogames.jooq.tables.records


import com.example.videogames.jooq.tables.Game

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GameRecord() : UpdatableRecordImpl<GameRecord>(Game.GAME), Record3<Int?, Int?, String?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var genreId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var gameName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<Int?, Int?, String?> = super.fieldsRow() as Row3<Int?, Int?, String?>
    override fun valuesRow(): Row3<Int?, Int?, String?> = super.valuesRow() as Row3<Int?, Int?, String?>
    override fun field1(): Field<Int?> = Game.GAME.ID
    override fun field2(): Field<Int?> = Game.GAME.GENRE_ID
    override fun field3(): Field<String?> = Game.GAME.GAME_NAME
    override fun component1(): Int? = id
    override fun component2(): Int? = genreId
    override fun component3(): String? = gameName
    override fun value1(): Int? = id
    override fun value2(): Int? = genreId
    override fun value3(): String? = gameName

    override fun value1(value: Int?): GameRecord {
        this.id = value
        return this
    }

    override fun value2(value: Int?): GameRecord {
        this.genreId = value
        return this
    }

    override fun value3(value: String?): GameRecord {
        this.gameName = value
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: String?): GameRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised GameRecord
     */
    constructor(id: Int? = null, genreId: Int? = null, gameName: String? = null): this() {
        this.id = id
        this.genreId = genreId
        this.gameName = gameName
    }
}
