/*
 * This file is generated by jOOQ.
 */
package com.example.videogames.jooq.tables.references


import com.example.videogames.jooq.tables.Databasechangeloglock
import com.example.videogames.jooq.tables.FlywaySchemaHistory
import com.example.videogames.jooq.tables.Game
import com.example.videogames.jooq.tables.GamePlatform
import com.example.videogames.jooq.tables.GamePublisher
import com.example.videogames.jooq.tables.Genre
import com.example.videogames.jooq.tables.Platform
import com.example.videogames.jooq.tables.Publisher
import com.example.videogames.jooq.tables.Region
import com.example.videogames.jooq.tables.RegionSales



/**
 * The table <code>video_games.DATABASECHANGELOGLOCK</code>.
 */
val DATABASECHANGELOGLOCK: Databasechangeloglock = Databasechangeloglock.DATABASECHANGELOGLOCK

/**
 * The table <code>video_games.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>video_games.game</code>.
 */
val GAME: Game = Game.GAME

/**
 * The table <code>video_games.game_platform</code>.
 */
val GAME_PLATFORM: GamePlatform = GamePlatform.GAME_PLATFORM

/**
 * The table <code>video_games.game_publisher</code>.
 */
val GAME_PUBLISHER: GamePublisher = GamePublisher.GAME_PUBLISHER

/**
 * The table <code>video_games.genre</code>.
 */
val GENRE: Genre = Genre.GENRE

/**
 * The table <code>video_games.platform</code>.
 */
val PLATFORM: Platform = Platform.PLATFORM

/**
 * The table <code>video_games.publisher</code>.
 */
val PUBLISHER: Publisher = Publisher.PUBLISHER

/**
 * The table <code>video_games.region</code>.
 */
val REGION: Region = Region.REGION

/**
 * The table <code>video_games.region_sales</code>.
 */
val REGION_SALES: RegionSales = RegionSales.REGION_SALES
