# App specific config
app:
  name: "videogames"

  config-properties:
    title: "videogames Development"
    banner:
      title: "Warning"
      content: "The videogames is under construction"

# Base logging.level.web controls web related logging, useful for development
# The library levels are set in logback-spring.xml
logging:
  level:
    web: "DEBUG"

# Spring config
spring:
  datasource:
    url: jdbc:h2:~/dev/capco/tut-spring-boot-kotlin/generated/flyway/h2;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS video_games\\;SET SCHEMA video_games
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        default_schema: VIDEO_GAMES
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true # turn off for tests
    baseline-on-migrate: true
    baseline-version: 1674208668
    clean-disabled: false
  liquibase:
    enabled: false

