/*
 * This file is generated by jOOQ.
 */
package com.example.videogames.jooq.tables


import com.example.videogames.jooq.VideoGames
import com.example.videogames.jooq.keys.KEY_PLATFORM_PRIMARY
import com.example.videogames.jooq.tables.records.PlatformRecord

import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Platform(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlatformRecord>?,
    aliased: Table<PlatformRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlatformRecord>(
    alias,
    VideoGames.VIDEO_GAMES,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>video_games.platform</code>
         */
        val PLATFORM: Platform = Platform()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlatformRecord> = PlatformRecord::class.java

    /**
     * The column <code>video_games.platform.id</code>.
     */
    val ID: TableField<PlatformRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>video_games.platform.platform_name</code>.
     */
    val PLATFORM_NAME: TableField<PlatformRecord, String?> = createField(DSL.name("platform_name"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<PlatformRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlatformRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>video_games.platform</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>video_games.platform</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>video_games.platform</code> table reference
     */
    constructor(): this(DSL.name("platform"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlatformRecord>): this(Internal.createPathAlias(child, key), child, key, PLATFORM, null)
    override fun getSchema(): Schema? = if (aliased()) null else VideoGames.VIDEO_GAMES
    override fun getIdentity(): Identity<PlatformRecord, Int?> = super.getIdentity() as Identity<PlatformRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlatformRecord> = KEY_PLATFORM_PRIMARY
    override fun `as`(alias: String): Platform = Platform(DSL.name(alias), this)
    override fun `as`(alias: Name): Platform = Platform(alias, this)
    override fun `as`(alias: Table<*>): Platform = Platform(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Platform = Platform(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Platform = Platform(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Platform = Platform(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Int?, String?> = super.fieldsRow() as Row2<Int?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
